# Generated by Django 2.2.7 on 2020-09-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0003_resturants_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='slug',
            field=models.SlugField(default='food-items'),
            preserve_default=False,
        ),
    ]
