# Generated by Django 2.2.7 on 2020-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0004_fooditems_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='foodelivery.OrderItem'),
        ),
    ]
