# Generated by Django 2.2.7 on 2020-09-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0006_auto_20200910_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
