# Generated by Django 2.2.7 on 2020-09-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0007_auto_20200911_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='fooditem',
            new_name='item',
        ),
    ]
