# Generated by Django 2.2.7 on 2020-09-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0010_auto_20200912_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='user',
        ),
    ]
