# Generated by Django 2.2.7 on 2020-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0014_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
