# Generated by Django 2.2.7 on 2020-09-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0015_shippingaddress_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phoneno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
