# Generated by Django 2.2.7 on 2020-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0016_auto_20200928_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodsimages'),
        ),
    ]
