# Generated by Django 2.2.7 on 2020-09-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0021_auto_20200929_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
