# Generated by Django 2.2.7 on 2020-10-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodelivery', '0024_auto_20201003_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customeruser',
        ),
    ]
